---
- name: Update apt package
  become: true
  hosts: all
  gather_facts: false
  tasks:
    # 共通処理
    - name: Common settings
      ansible.builtin.import_role:
        name: common

- name: Create work user
  become: true
  hosts: web, batch
  vars_files:
    - vars/application.yml
  tasks:
    - name : Create work user group
      ansible.builtin.group:
        name: "{{ default_user_group }}" 
        state: present

    - name : Create work user 
      ansible.builtin.user:
        name: "{{ default_user_name }}" 
        group: "{{ default_user_group }}" 
        password: "{{ default_user_password | password_hash('sha512') }}"
        groups: sudo
        shell: "/bin/bash"
        append: true

- name: Deploy web system
  become: true
  vars_files:
    - vars/application.yml
    - vars/infrastructure.yml
  hosts: web
  gather_facts: true
  tasks:
    # Web Serverのセッティング
    - name: Webserver Setting
      ansible.builtin.import_role:
        name: web
    - name: NFS Setting
      ansible.builtin.import_role:
        name: nfs 
  tags: 
  - "web"

- name: Deploy batch system
  become: true
  vars_files:
    - vars/application.yml
    - vars/infrastructure.yml
  hosts: batch
  gather_facts: true
  tasks:
    # Web Serverのセッティング
    - name: Batch server Setting
      ansible.builtin.import_role:
        name: batch
    - name: NFS Setting
      ansible.builtin.import_role:
        name: nfs 
  tags: 
  - "batch"

- name: Setting database server
  become: true
  vars_files:
    - vars/infrastructure.yml
  hosts: db
  gather_facts: true
  tasks:
    - name: Database Setting
      ansible.builtin.import_role:
        name: db
      vars:
        postgres_user: "{{ database.application.admin_user }}"
        postgres_password: "{{ database.application.admin_password }}"
        monitor_user: "{{ database.application.monitor.user }}"
        monitor_password: "{{ database.application.monitor.password }}"
        zabbix_server: "{{ local_zabbix_agent_server }}"
        zabbix_serveractive: "{{ local_zabbix_agent_serveractive }}"
  tags:
  - "db"

- name: Setup management server
  become: true
  vars_files:
    - vars/infrastructure.yml
  hosts: mng 
  gather_facts: true
  tasks:
    - name: Database Setting
      ansible.builtin.import_role:
        name: mng
      vars:
        zabbix_database_admin_username: "{{ database.management.admin_user }}"
        zabbix_database_admin_password: "{{ database.management.admin_password }}"
        zabbix_database_host: "{{ database.management.zabbix.host }}"
        zabbix_database_name: "{{ database.management.zabbix.name }}"
        zabbix_database_username: "{{ database.management.zabbix.username }}"
        zabbix_database_password: "{{ database.management.zabbix.password }}"
        zabbix_database_schema: "{{ database.management.zabbix.schema }}"
        monitor_database_name: "{{ database.application.monitor.name }}"
        monitor_database_user: "{{ database.application.monitor.user }}"
        monitor_database_password: "{{ database.application.monitor.password }}"
        monitor_database_server: "{{ database.application.monitor.host }}"
  tags: 
  - "mng"