---
- name: Update apt package
  become: true
  hosts: all
  vars_files:
    - vars/common.yml
  gather_facts: false

  tasks:
    # 共通処理
    - name: Common settings
      ansible.builtin.import_role:
        name: common
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"

- name: Deploy web system
  become: true
  vars_files:
    - vars/nfs.yml
    - vars/common.yml
    - vars/zabbix.yml
    - vars/lb.yml
  hosts: web
  gather_facts: true

  tasks:
    # Web Serverのセッティング
    - name: Webserver Setting
      ansible.builtin.import_role:
        name: web
  tags: 
  - "web"
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"

- name: Deploy batch system
  become: true
  vars_files:
    - vars/nfs.yml
    - vars/common.yml
    - vars/zabbix.yml
  hosts: batch
  gather_facts: true
  tasks:
    # Web Serverのセッティング
    - name: Batch server Setting
      ansible.builtin.import_role:
        name: batch
  tags: 
  - "batch"
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"

- name: Setting database server
  become: true
  vars_files:
    - vars/common.yml
    - vars/zabbix.yml
    - roles/db/vars/postgresql.yml
    - roles/db/vars/root.yml
    - roles/db/vars/user.yml
  hosts: db
  gather_facts: true
  tasks:
    - name: Database Setting
      ansible.builtin.import_role:
        name: db
  tags:
  - "db"
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"

- name: Setup management server
  become: true
  vars_files:
    - vars/nfs.yml
    - vars/common.yml
    - vars/lb.yml
  hosts: mng 
  gather_facts: true
  tasks:
    - name: Database Setting
      ansible.builtin.import_role:
        name: mng
  tags: 
  - "mng"
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"
    ansible_os_family: "Ubuntu"