---
- name: Update apt package
  become: true
  hosts: all
  gather_facts: false
  tasks:
    # 共通処理
    - name: Common settings
      ansible.builtin.import_role:
        name: common

- name: Create work user
  become: true
  hosts: web, batch
  vars_files:
    - vars/application.yml
  tasks:
    - name : Create work user group
      ansible.builtin.group:
        name: "{{ default_user_group }}" 
        state: present

    - name : Create work user 
      ansible.builtin.user:
        name: "{{ default_user_name }}" 
        group: "{{ default_user_group }}" 
        password: "{{ default_user_password | password_hash('sha512') }}"
        groups: sudo
        shell: "/bin/bash"
        append: true

- name: Deploy web system
  become: true
  vars_files:
    - vars/application.yml
    - vars/infrastructure.yml
  hosts: web
  gather_facts: true
  tasks:
    # Web Serverのセッティング
    - name: Webserver Setting
      ansible.builtin.import_role:
        name: web
    - name: NFS Setting
      ansible.builtin.import_role:
        name: nfs 
  tags: 
  - "web"

- name: Deploy batch system
  become: true
  vars_files:
    - vars/application.yml
    - vars/infrastructure.yml
  hosts: batch
  gather_facts: true
  tasks:
    # Web Serverのセッティング
    - name: Batch server Setting
      ansible.builtin.import_role:
        name: batch
    - name: NFS Setting
      ansible.builtin.import_role:
        name: nfs 
  tags: 
  - "batch"

- name: Setting database server
  become: true
  vars_files:
    - vars/infrastructure.yml
    - roles/db/vars/postgresql.yml
    - roles/db/vars/root.yml
    - roles/db/vars/user.yml
  hosts: db
  gather_facts: true
  tasks:
    - name: Database Setting
      ansible.builtin.import_role:
        name: db
  tags:
  - "db"

- name: Setup management server
  become: true
  vars_files:
    - vars/infrastructure.yml
  hosts: mng 
  gather_facts: true
  tasks:
    - name: Database Setting
      ansible.builtin.import_role:
        name: mng
  tags: 
  - "mng"