---
- name: Update apt package
  become: true
  hosts: all
  vars_files:
    - vars/common.yml
  gather_facts: false

  tasks:
    # 共通処理
    - name: Common settings
      ansible.builtin.import_role:
        name: common
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"

- name: Deploy web system
  become: true
  vars_files:
    - vars/common.yml
  hosts: web
  gather_facts: false

  tasks:
    # Web Serverのセッティング
    - name: Webserver Setting
      ansible.builtin.import_role:
        name: web
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"

- name: Setting database server
  become: true
  vars_files:
    - vars/common.yml
    - roles/db/vars/root.yml
  hosts: db
  gather_facts: false
  tasks:
    - name: Webserver Setting
      ansible.builtin.import_role:
        name: db
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"