version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myadmin
      POSTGRES_PASSWORD: myadmin_pass
      POSTGRES_DB: pgcrypto_test
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myadmin"]
      interval: 30s
      timeout: 10s
      retries: 5
