---
- name: Restart PostgreSQL
  systemd:
    name: postgresql
    state: restarted
    enabled: yes

- name : Restart Zabbix
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ zabbix_service_list }}"

