---
- name: Install package
  ansible.builtin.apt:
    name: 
    - nfs-common
    state: present

- name: Download repository
  ansible.builtin.get_url: 
    url : https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2%2Bubuntu24.04_all.deb
    dest: /tmp

- name: dpkg zabbix repos
  shell:  dpkg -i /tmp/zabbix-release_7.0-2%2Bubuntu24.04_all.deb

- name: Update apt repository
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600  # 1時間有効なキャッシュを使用

- name: Install zabbix package
  ansible.builtin.apt:
    name: 
    - zabbix-server-pgsql 
    - zabbix-frontend-php
    - php8.3-pgsql 
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent
    - postgresql-client-common
    state: present
