---
- name: load vars_file
  include_vars:
    dir: ../vars
    files_matching:
    - odbc.yml
    - zabbix_database.yml
    - zabbix_server.yml

- name: Install zabbix package
  ansible.builtin.apt:
    name: 
    - postgresql-{{ postgresql_version }}
    - postgresql-contrib
    - postgresql-client
    - postgresql-client-common
    - libpq-dev
    - zabbix-server-pgsql 
    - zabbix-frontend-php
    - php8.3-pgsql 
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent
    - language-pack-ja-base
    - language-pack-ja
    - ibus-mozc
    - unixodbc
    - unixodbc-dev
    - odbc-postgresql
    state: present

- name: Setup Zabbix database
  ansible.builtin.include_tasks: zabbix_database.yml

- name: Setup Nginx config
  ansible.builtin.include_tasks: zabbix_nginx.yml

- name: Setup Zabbix server 
  ansible.builtin.include_tasks: zabbix_server.yml

- name: Setup odbc 
  ansible.builtin.include_tasks: odbc.yml

- name: Setup rsyslog
  ansible.builtin.include_tasks: syslog.yml