---
- name: Install zabbix package
  ansible.builtin.apt:
    name: 
    - zabbix-server-pgsql 
    - zabbix-frontend-php
    - php8.3-pgsql 
    - zabbix-nginx-conf
    - zabbix-sql-scripts
    - zabbix-agent
    - postgresql-client
    - postgresql-client-common
    - language-pack-ja-base
    - language-pack-ja
    - ibus-mozc
    state: present

- name: Setup Zabbix database
  ansible.builtin.include_tasks: zabbix_database.yml

- name: Setup Zabbix server 
  ansible.builtin.include_tasks: zabbix_server.yml

- name: Setup Nginx config
  ansible.builtin.include_tasks: zabbix_nginx.yml
