---
- name: Install rsyslog
  ansible.builtin.apt:
    name: 
    - rsyslog

- name: Configure rsyslog for nginx
  ansible.builtin.copy:
    src: ./files/rsyslog.nginx.conf
    dest: /etc/rsyslog.d/nginx.conf

- name: Configure rsyslog for elb
  ansible.builtin.copy:
    src: ./files/rsyslog.elb.conf
    dest: /etc/rsyslog.d/elb.conf

- name: Configure rsyslog to listen on UDP and TCP ports
  lineinfile:
    path: /etc/rsyslog.conf
    line: "{{ item }}"
    state: present
  loop:
    - "module(load=\"imudp\")"
    - "input(type=\"imudp\" port=\"514\")"
  notify: Restart rsyslog

- name: Configure logrotate for nginx
  ansible.builtin.copy:
    src: ./files/logrotate.nginx.conf
    dest: /etc/logrotate.d/rsyslog.nginx
  notify: Restart rsyslog