---
- name: configure / Configure PostgreSQL. Set listen_addresses.
  lineinfile: 
    dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp="listen_addresses =" line="listen_addresses = '*'"
    state=present

- name: Update pg_hba
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    contype: host
    source: 192.168.0.0/24
    method: md5
    state: present
  notify: Restart PostgreSQL

- name: Change postgres root password
  user:
    name: "{{ zabbix_database_admin_username }}"
    password: "{{ zabbix_database_admin_password | password_hash('sha256')}}"

- name: Create zabbix database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ zabbix_database_name }}"
    port: "{{ postgresql_port }}"
    state: present

- name: Create database user
  become_user: postgres
  community.postgresql.postgresql_user:
    db: "{{ zabbix_database_name }}"
    name: "{{ zabbix_database_username }}"
    password: "{{ zabbix_database_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
    port: "{{ postgresql_port }}"
    encrypted: yes
    state: present

# ユーザ毎にスキーマを作成する
- name: Create zabbix schema
  become_user: postgres
  community.postgresql.postgresql_schema:
    name: "{{ zabbix_database_schema }}"
    database: "{{ zabbix_database_name }}"
    owner: "{{ zabbix_database_username }}"
    port: "{{ postgresql_port }}"
    state: present

# デフォルトスキーマ変更
- name: Set default search_path
  become_user: postgres
  community.postgresql.postgresql_query:
    db: postgres
    port: "{{ postgresql_port }}"
    query: |
      ALTER USER {{ zabbix_database_username }} SET search_path TO {{ zabbix_database_schema }}, public;

# 初期化用DBを登録
- name: configure / initialize database
  community.postgresql.postgresql_db:
    name: "{{ zabbix_database_name }}"
    login_host: "{{ zabbix_database_host }}"
    login_user: "{{ zabbix_database_username }}"
    login_password: "{{ zabbix_database_password }}"
    port: "{{ postgresql_port }}"
    state: "restore"
    target: "/usr/share/zabbix-sql-scripts/postgresql/server.sql.gz"