---
- name: Setup Zabbix Server(Database host)
  ansible.builtin.lineinfile:
    path: "{{ zabbix_conf_path }}"
    regexp: "^DBHost=localhost"
    line: "DBHost={{ zabbix_database_host }}"
    backup: true
    state: present

- name: Setup Zabbix Server(Database schema)
  ansible.builtin.lineinfile:
    path: "{{ zabbix_conf_path }}"
    regexp: "^DBSchema="
    line: "DBSchema={{ zabbix_database_schema }}"
    backup: true
    state: present

- name: Setup Zabbix Server(Database name)
  ansible.builtin.lineinfile:
    path: "{{ zabbix_conf_path }}"
    regexp: "^DBName="
    line: "DBName={{ zabbix_database_name }}"
    backup: true
    state: present

- name: Setup Zabbix Server(Database user)
  ansible.builtin.lineinfile:
    path: "{{ zabbix_conf_path }}"
    regexp: "^DBUser="
    line: "DBUser={{ zabbix_database_username }}"
    backup: true
    state: present

- name: Setup Zabbix Server(Database password)
  ansible.builtin.lineinfile:
    path: "{{ zabbix_conf_path }}"
    regexp: "^DBPassword="
    line: "DBPassword={{ zabbix_database_password }}"
    backup: true
    state: present

- name: Setup Zabbix Server(Database port)
  ansible.builtin.lineinfile:
    path: "{{ zabbix_conf_path }}"
    regexp: "^DBPort="
    line: "DBPort={{ postgresql_port }}"
    backup: true
    state: present
    
- name: Load locate generate
  ansible.builtin.shell: locale-gen
  args:
    executable: /bin/bash

- name: zabbix | update zabbix web config
  template:
    src: ./templates/zabbix.web.conf.php.j2
    dest: "{{ zabbix_web_conf_path }}"
    backup: true
  notify: Restart Zabbix