---
# Nginxデフォルトのsite-availableを削除する
# (zabbix.confと内容が冗長。site-availableが後勝ちとなってしまうため)
- name: disabled site-enabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: nginx.confの編集 - server_tokensの無効
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: present
    insertbefore: 'include /etc/nginx/conf.d/\*.conf;'
    line: '    server_tokens off;'

- name: deply nginx.conf
  template:
    src: ./templates/nginx.conf.j2
    dest: "{{ zabbix_nginx_conf_path }}"
    backup: true