---
- name: Install package
  ansible.builtin.apt:
    name: 
    - git
    - nginx
    state: present

- name: disabled site-enabled
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: deply nginx.conf
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    backup: true

- name: Zabbix agent Setting
  ansible.builtin.import_role:
    name: community.zabbix.zabbix_agent
  vars:
    zabbix_agent_hostname: "Web Server"
    zabbix_agent_server: "{{ local_zabbix_agent_server }}"
    zabbix_agent_serveractive: "{{ local_zabbix_agent_serveractive }}"

- name: Setup NFS
  ansible.builtin.include_tasks: nfs.yml


