---
- name: Install package
  ansible.builtin.apt:
    name: 
    - git
    - nginx
    - certbot
    - python3-certbot-dns-sakuracloud
    - nfs-common
    state: present


- name: create sakura cloud secrets.
  copy:
    dest: ~/.sakura
    content: |
      dns_sakuracloud_api_token = "{{ lookup('env', 'SAKURACLOUD_ACCESS_TOKEN') }}"
      dns_sakuracloud_api_secret = "{{ lookup('env', 'SAKURACLOUD_ACCESS_TOKEN_SECRET') }}"
    mode: '0600'

- name: check file exists
  ansible.builtin.stat:
    path: "/etc/letsencrypt/live/{{ domain }}"
  register: ssl_data

- name: certbot certonly
  expect:
    command: >
      certbot certonly
      --dns-sakuracloud
      --dns-sakuracloud-credentials /root/.sakura
      --dns-sakuracloud-propagation-seconds 90
      -d *.{{ domain }}
      -d {{ domain }}
      -m {{ email }}}
      --agree-tos
    responses:
      '(Y)es/(N)o:': 'Y'
  register: certbot_output 
  when: not ssl_data.stat.exists

  # NginxをSSL化する
- name: deply nginx_ssl.conf
  template:
    src: ./files/nginx.ssl.conf.j2
    dest: /etc/nginx/conf.d/nginx.ssl.conf

- name: Enable certbot timer
  systemd:
    name: certbot.timer
    enabled: true
    state: started

- name: Mount up sakura cloud nfs
  ansible.posix.mount:
    src: "{{ nfs_src }}"
    path: /data
    fstype: nfs
    opts: defaults
    dump: 0    #バックアップしない
    passno: 0  # fsck無効 
    state: mounted
