---
# Zabbix
zabbix_conf_path: /etc/zabbix/zabbix_server.conf
zabbix_nginx_conf_path: /etc/zabbix/nginx.conf
zabbix_web_conf_path: /etc/zabbix/web/zabbix.conf.php

zabbix_service_list:
- zabbix-server
- zabbix-agent
- nginx
- php8.3-fpm