---
- name: Setup postgresql
  become: true
  become_method: sudo
  ansible.builtin.apt:
    name: 
    - postgresql-{{ postgresql_version }}
    - postgresql-contrib
    - nfs-common
    - libpq-dev
    state: present

- name: Copy new pg_hba.conf for all users
  copy:
    src: ./files/pg_hba.conf
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0600'
  notify: Restart PostgreSQL # See ./handlers/main.yml

- name: Change postgres password
  user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password | password_hash('sha256')}}"

- name: Create zabbix database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: zabbix
    port: "{{ postgresql_port }}"
    state: present

- name: Create database user
  become_user: postgres
  community.postgresql.postgresql_user:
    db: "{{ item.db }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE
    port: "{{ postgresql_port }}"
    encrypted: yes
    state: present
  with_items: "{{ postgresql_users }}"